# Generated by Django 5.2.5 on 2025-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="6596121.png", upload_to="avatars/"),
        ),
    ]
